[workspace]

members = [
    "app/src-tauri",
    "core",
    "service",
    "web",
    "examples/*",
]

[workspace.dependencies]
rand = { version = "0.8" }
thiserror = { version = "1.0" }
tokio = { version = "1.29", features = ["full"] }
warp = { version = "0.3"}
